# https://github.com/GoogleCloudPlatform/gcr-cleaner/blob/main/docs/deploy-github-actions.md
name: 'gcr-cleaner'

on:
  schedule:
    - cron: '0 0 */1 * *' # runs daily
  workflow_dispatch: # allows for manual invocation

jobs:
  gcr-cleaner:
    runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      # https://github.com/docker/login-action#google-artifact-registry-gar
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/837339871826/locations/global/workloadIdentityPools/gcr-cleaner-pool/providers/gcr-cleaner-provider'
          service_account: 'gcr-cleaner@longboard-linebot.iam.gserviceaccount.com'

      # configure based on your registry
      - uses: 'docker/login-action@v2'
        with:
          registry: us-central1-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      # customize based on the gcr-cleaner flags
      - uses: 'docker://us-docker.pkg.dev/gcr-cleaner/gcr-cleaner/gcr-cleaner-cli'
        with:
          args: >-
            -repo=us-central1-docker.pkg.dev/longboard-linebot/gcf-artifacts/longboard--linebot--production
            -repo=us-central1-docker.pkg.dev/longboard-linebot/gcf-artifacts/longboard--linebot--stage
            -grace=48h